security:
  jwt:
      secret-key: verysecretkeyohmygodwhyisitsosecretdonttellanybody
server:
  port: 9000
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: admin123
    url: jdbc:oracle:thin:@localhost>:1521/XE
    username: amaris